htmx config in js
gone/django-hydra pull request #590
Opened 2023-07-25 15:55 UTC by edcohen08

2023-08-01 21:39 UTC, gone commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/main.ts
> +    htmx.ajax("GET", dest, { target: "body", swap: "morph" });
should this be alpine morph not morph?

2023-10-19 17:51 UTC, brianedelman requested changes
Few notes for you but looks good otherwise

2023-10-19 17:51 UTC, brianedelman commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/index.ts
> -export type AlpineDataCallback = (...initialStateArgs: unknown[]) => AlpineComponent
So index.ts is empty now? any reason to separate it from main then?

2023-10-19 17:51 UTC, brianedelman commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/main.ts
> +htmx.on("htmx:beforeOnLoad", (event:any) => {
I think Event is the proper type here rather than any

2023-10-19 17:51 UTC, brianedelman commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/main.ts
> +    //switch to morph when ideomorph is ready
IMO you should link to docs about what this is referring to

2023-10-19 17:51 UTC, brianedelman commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/main.ts
> +  onEvent: function(name: string, evt: any) {
I would bet evt is Event type as  well

2023-10-19 17:51 UTC, brianedelman commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/input.ts
> +      }
Could be a little cleaner IMO
this.value = this.value === "None" ? "" : this.value;

if (this.$refs?.input) {
  // Toggle the focused state on an input when an initial value is set.
  this.active = !this.active;
}

2023-10-19 17:52 UTC, gone commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/index.ts
> -export type AlpineDataCallback = (...initialStateArgs: unknown[]) => AlpineComponent
not that I know of, I just know index is sometimes a special name and wasn't sure if we needed it

2023-10-19 19:01 UTC, merged